augmentors:
  # float values should range from 0 - 1

  back_translation:
    hops: 2

  noise_injection:
    typo_params:
      word_percentage: 0.2
      char_percentage: 0.1
      min_augment: 1
      max_augment: 2
    swapletter_params:
      word_percentage: 0.2
      char_percentage: 0.1
      min_augment: 1
      max_augment: 2

  random_augmentation:
    synonym_params:
      word_percentage: 0.2
      min_augment: 1
      max_augment: 2
    swap_params:
      word_percentage: 0.2
      min_augment: 1
      max_augment: 2
    delete_params:
      word_percentage: 0.2
      min_augment: 1
      max_augment: 2
    insert_count: 1
    mixup_count: 2
    stopwords: ["it", "as"]
